### ISSUE TITLE
php-fpm should use a socket instead of a port

### ISSUE THREAD

**Issue by carsonoid** [abiosoft/caddy-docker#10]
I hit a bit of an odd problem using this in our environment. Basically I needed caddy to listen on 9000 but since php was using it the container would crash. It's probably best to use a unix socket for php-fpm since it doesn't talk to anyone but Caddy anyway.

I solved this in the Dockerfile with:

```
RUN  sed -i 's|listen\s*=.*|listen = /var/run/php5-fpm.sock|' /etc/php/php-fpm.conf
```

And then I set the Caddyfile directive

```
fastcgi / unix:/var/run/php5-fpm.sock php
```

Maybe it's too odd to pull into the mainstream image. But I thought I'd bring it up anyway. Now caddy can bind anywhere it wants without conflict.

**Comment by abiosoft** [comment]
You have a point. I would have added it to the image but this would break anyone currently using it as their configuration will rely on port.

Thanks.

**Comment by abiosoft** [comment]
I'll be closing this as the current setup works for most people. Anyone willing to do this can follow the instructions above to get a custom image.

Thanks.
