### ISSUE TITLE
--env ACME_AGREE=true

### ISSUE THREAD

**Issue by swallace21** [abiosoft/caddy-docker#101]
Adding this to docker start:
--env ACME_AGREE=true

BUT, Portainer still reports: 
ACME_AGREE | false

**Comment by abiosoft** [comment]
Ensure you're on version 0.10.12.

**Comment by swallace21** [comment]
Thanks for the quick response. I checked and the version is 0.10.12.

Got it to work, syntax error on my part. Was adding t the ACME_AGREE env to the end which was wrong.

Works:
docker run --name caddy -d -p 80:80 -p 443:443 --env ACME_AGREE="true" -v $MYPATH/Caddyfile:/etc/Caddyfile -v $MYPATH/srv:/srv -v $MYPATH/certs:/root/.caddy abiosoft/caddy
