### ISSUE TITLE
PHP Tokenizer module missing

### ISSUE THREAD

**Issue by wywywywy** [abiosoft/caddy-docker#105]
Hi,

The Tokenizer module for PHP is missing.  This is a standard module that is usually compiled into PHP since years ago, except for the Alpine build.  It is widely used in things like Drupal and Vanilla Forums etc.

It is separately available in this apk package `php7-tokenizer`.

Obviously we can create a new image from caddy:php and get it in, but can we have it added to this repo for the convenience of everyone, and to keep it in line with a standard PHP installation please?

Thanks.

**Comment by abiosoft** [comment]
It has been added to the repo and is available in the `:php` image. But to have it tied to a specific version e.g. `:0.10.14-php`, you have to wait till the next release.

**Comment by wywywywy** [comment]
Works great now thank you for sorting it out so quickly.
