### ISSUE TITLE
Inconsistent parsing of command line flags

### ISSUE THREAD

**Issue by ithinkihaveacat** [abiosoft/caddy-docker#107]
`caddy` parses command line options inconsistently: in some cases both `-option value` and `-option=value` is accepted, but in others only the first is accepted.

Both forms accepted for `-type`:

```sh
$ caddy -type http -validate
Caddyfile is valid
$ caddy -type=http -validate
Caddyfile is valid
```

Only one for accepted for `-http2`:

```sh
$ caddy -http2 false -validate
2018/04/26 10:32:45 args:2 - Error during parsing: Unknown directive 'false'
$ caddy -http2=false -validate
Caddyfile is valid
```

The documentation does not suggest there would be any difference in the way these options are parsed:

```text
  -http2
    	Use HTTP/2 (default true)
...
  -type string
    	Type of server to run (default "http")
```

**Comment by abiosoft** [comment]
It is not inconsistent, it is how Go parses command line. Booleans are different.

To set boolean you need `=` i.e. `-http2=false`.

**Comment by ithinkihaveacat** [comment]
Ah, I see. In that case, can the documentation be changed to make this clear? I suspect many users are not familiar with the details of go's command-line parsing behavior (or even that caddy is written in go).

Perhaps:

```text
-http2=true|false
```

**Comment by abiosoft** [comment]
Yeah you're right end users may not know. Noted.
