### ISSUE TITLE
Support for net plugin

### ISSUE THREAD

**Issue by etique57** [abiosoft/caddy-docker#110]
Hello,

I'm successfully running one docker instance for my HTTP frontend. I'm trying to set up a second caddy instance with the net plugin to support mail redirection, but this time it doesn't work.

Here's what I'm doing:
Building an image with the net plugin:
```
docker build -t caddy_net --build-arg plugins=net github.com/abiosoft/caddy-docker.git
```
Caddyfile:
```
proxy :143 :143 {
       host server
}
```
Running the image with this command:
`docker run --name caddy-net -e "ACME_AGREE=true" -v /home/caddy/conf/Caddyfile-net:/etc/Caddyfile -v /home/caddy/srv:/srv -v /home/caddy/certs:/root/.caddy -v /home/caddy/log:/var/log/caddy -p 143:143 caddy_net --type=net`

But it instantly exits though without error on stdout.

Am I doing something wrong?

Thanks!

**Comment by etique57** [comment]
I tried with simple binary I downloaded directly from caddy and it works.

**Comment by abiosoft** [comment]
I don't know how I forgot to update this issue. This has been fixed a long time ago.
