### ISSUE TITLE
Telemetry not being disabled properly

### ISSUE THREAD

**Issue by enriquecaballero** [abiosoft/caddy-docker#111]
Just pulled and added the `telemetry: false` arg yet I see...
```
caddy_1  | 2018/05/10 22:18:44 [INFO] Sending telemetry: success
```
...in my logs.

**Comment by abiosoft** [comment]
use the `ENABLE_TELEMETRY` env var instead.

https://github.com/abiosoft/caddy-docker#telemetry-stats

**Comment by enriquecaballero** [comment]
There seems to be a disconnect here. Shouldn't https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile#L8 match https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile#L8?

**Comment by abiosoft** [comment]
Nope, not at all. There are two different things.

The first one generates a configurable caddy, the second one simply defaults the env var to enabled.

**Comment by enriquecaballero** [comment]
OH! Gotcha. Cool. I'll wait until the builds are done. Thanks!

**Comment by abiosoft** [comment]
It should be fine now.

**Comment by abiosoft** [comment]
@enriquecaballero this decision has been reversed after careful discussion with Caddy team members due to the relevance of the build time config to the Telemetry project.

However, the option to opt out still remains but it is now provided via a separate tag. https://github.com/abiosoft/caddy-docker#telemetry-stats

**Comment by abiosoft** [comment]
> So just pass 0.11.0-no-stats to the version arg?

Yeah. Unfortunately, like yesterday the builds are still ongoing. The tag may not be live for the next one hour.

**Comment by abiosoft** [comment]
Specify `version` as `0.11.0` and `dockerfile` as `Dockerfile-no-stats
