### ISSUE TITLE
Ability to use staging ACME environment?

### ISSUE THREAD

**Issue by Notifium** [abiosoft/caddy-docker#117]
Hi,
Caddy allows the use of -ca option to define the acme URL, allowing the staging environment to be used for testing.

Is a similar thing available in caddy-docker?

Regards,
Andy

**Comment by abiosoft** [comment]
Yeah, just pass additional arguments to the container.
```
docker run abiosoft/caddy -ca <staging url>
```

**Comment by Notifium** [comment]
Ah thanks so much.

**Comment by throrin19** [comment]
and with a docker-compose config ?
