### ISSUE TITLE
Docker Exec

### ISSUE THREAD

**Issue by bc24fl** [abiosoft/caddy-docker#12]
Thanks for taking the time to create this docker.  When I try to enter the docker container i receive an error.  Did you purposely disable /bin/bash?  

sudo docker exec -it mycaddy /bin/bash

rpc error: code = 2 desc = "oci runtime error: exec failed: exec: \"/bin/bash\": stat /bin/bash: no such file or directory"

**Comment by abiosoft** [comment]
Yeah, Alpine does not have bash by default. Use sh instead.

```
docker run -it mycaddy sh
```
