### ISSUE TITLE
Cloudflare DNS provider not installing

### ISSUE THREAD

**Issue by BuckinghamIO** [abiosoft/caddy-docker#121]
I keep getting Unsupported DNS provider even though I am setting cloudflare in the plugins build arg

I've tried setting it in my compose file and also in the docker file but it never gets installed?

mm_nginx:
    build:
      context: ./containers/caddy
      args:
        plugins: "cloudflare,git,filemanager,cors,realip,expires,cache"
    image: registry.hub.docker.com/buckinghamio/minecraftmarket-nginx:${BUILD_TAG:-latest}
    container_name: mm-nginx
    restart: unless-stopped
    depends_on:
      - minecraftmarket
      - mm_redis
    volumes:
      - nginx_data:/etc/resty-auto-ssl
      - caddy_data:/etc/caddycerts

ARG plugins="cloudflare,git,filemanager,cors,realip,expires,cache"
FROM abiosoft/caddy

**Comment by derevandal** [comment]
Hi, did you try to use `tls.dns.cloudflare` instead of `cloudflare` ?

**Comment by abiosoft** [comment]
Actually, `cloudfare` is the correct one. 
> Hi, did you try to use tls.dns.cloudflare instead of cloudflare ?

@BuckinghamIO set `build` as `github.com/abiosoft/caddy-docker` instead. You don't need a separate `Dockerfile`.

**Comment by derevandal** [comment]
@abiosoft 
I made a [fork](https://github.com/derevandal/caddy-docker) and add cloudflare as build args in dockerfile to use um my swarm...

```yml
ARG plugins="git,filemanager,cors,realip,expires,cache,docker,datadog,minify,nobots,prometheus,ratelimit,webdav,cloudflare"
```

And error still apears:

```bash
/etc/Caddyfile:3 - Error during parsing: Unsupported DNS provider 'cloudflare'
```

**Comment by dodekeract** [comment]
@BuckinghamIO @derevandal Works fine for my local dev environment: https://github.com/dodekeract/cloudflocaddy

Maybe this can help you troubleshoot the issue?

**Comment by abiosoft** [comment]
Are you still having this issue?
