### ISSUE TITLE
Variable ACME_AGREE not interpolated?

### ISSUE THREAD

**Issue by hartwork** [abiosoft/caddy-docker#122]
Hi Abiola,

thanks for sharing your Caddy images with the free software community!
(I based my [reverse proxy](https://github.com/hartwork/docker-ssl-reverse-proxy) upon your images.)

One thing caught my attention: With the way that `ACME_AGREE` is used in ..
```
CMD ["--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=$ACME_AGREE"]
```
.. `$ACME_AGREE` is not interpolated by Docker because of the use of `CMD [..]` syntax, right?
Is anything else interpolating `ACME_AGREE`, e.g. `/bin/parent` in `ENTRYPOINT`?

Here's proof that Docker itself does not interpolate it (on a Bash terminal):
```console
$ echo $'#! /bin/sh\nset -x\nexec "$@"' > parent && chmod +x parent && docker run -v "${PWD}"/parent:/bin/parent abiosoft/caddy:no-stats |& head -n2
+ exec caddy --conf /etc/Caddyfile --log stdout --agree=$ACME_AGREE
invalid boolean value "$ACME_AGREE" for -agree: strconv.ParseBool: parsing "$ACME_AGREE": invalid syntax
```
I'm probably missing something?

Best, Sebastian

**Comment by abiosoft** [comment]
Yeah, docker doesn't and that's why I wrote the [parent](https://github.com/abiosoft/parent) script to get around it. parent handles the interpolation as well as signal forwarding to caddy process.

**Comment by abiosoft** [comment]
This is actually not an issue so I'll be closing, but we can continue discussion.

**Comment by hartwork** [comment]
Thansk! Found it in https://github.com/abiosoft/parent/blob/master/main.go#L61 now.
