### ISSUE TITLE
Support for quic

### ISSUE THREAD

**Issue by Trree** [abiosoft/caddy-docker#123]
Since I downloaded carry from the docker hub, I don't want to update the Dockerfile to support quic. When I use docker run it will report the following error. How can I do it?

> docker run -d -p 2015:2015 abiosoft/caddy caddy -quic
>  Error during parsing: Unknown directive 'caddy'

**Comment by abiosoft** [comment]
you don't need `caddy`.

```
docker run -d -p 2015:2015 abiosoft/caddy -quic
```
