### ISSUE TITLE
path to Caddyfile

### ISSUE THREAD

**Issue by mbana** [abiosoft/caddy-docker#128]
Can you allow passing in the path to the `Caddyfile`, please. Something like below:

```dockerfile
...
ENV CADDYFILE "/etc/Caddyfile"
CMD ["--conf", "$CADDYFILE", "--log", "stdout", "--agree=$ACME_AGREE"]
...
```

Thanks,

**Comment by abiosoft** [comment]
The Caddyfile is at `/etc/Caddyfile`. All you have to do is mount it in the container https://github.com/abiosoft/caddy-docker#using-local-caddyfile-and-sites-root

**Comment by abiosoft** [comment]
I'll be closing this as well as it is not an issue. `$ACME_AGREE` was a special case.
