### ISSUE TITLE
Use alpine:3.8 to get PHP 7.2

### ISSUE THREAD

**Issue by wecc** [abiosoft/caddy-docker#129]
Is there anything preventing the use of `alpine:3.8` over `alpine:3.7` in the various Dockerfiles? (At least) for the PHP-image it would great if it could be based off of `alpine:3.8` since that would give us PHP 7.2 instead of PHP 7.1.

I'd be happy to provide a PR if the above makes sense 👍

**Comment by abiosoft** [comment]
Sure, go ahead.
