### ISSUE TITLE
Docker Build - invalid Reference format

### ISSUE THREAD

**Issue by psyciknz** [abiosoft/caddy-docker#137]
I'm just trying to run the build command from the readme.

```
docker build --build-arg     plugins=filemanager,git,linode     github.com/abiosoft/caddy-docker.git                                           Sending build context to Docker daemon 188.4 kB
Step 1/22 : FROM abiosoft/caddy:builder as builder
Error parsing reference: "abiosoft/caddy:builder as builder" is not a valid repository/tag: invalid reference format
```

What am I missing from the doco that should let me add plugins.  I've tried downloading the source into a folder, and removing the  github.com/abiosoft/caddy-docker.git with . and get the same error.

I assume there's something missing on my system

**Comment by abiosoft** [comment]
You're likely using a very old version of Docker that do not support [multi-stage builds](https://docs.docker.com/develop/develop-images/multistage-build/). It was introduced in version 17.05.

**Comment by psyciknz** [comment]
Awsome thanks for the pointer.  Docker removed, docker-ce installed, and currently building.
