### ISSUE TITLE
File Browser broken in latest image

### ISSUE THREAD

**Issue by wraeuk** [abiosoft/caddy-docker#139]
Running caddy:latest with `filemanager` directive leads it to never load (hangs on the loading animation).
I rolled back to caddy:0.11.0 and it's running just fine, so there's been a commit somewhere that's broken it.

EDIT: oh if it helps I ran up a quick container just for File Browser and it also broke when being proxied through caddy:latest (but worked fine internally)

**Comment by abiosoft** [comment]
I would suggest to stick to 0.11.0 for now. I've temporarily removed file manager until this issue is fixed https://github.com/filebrowser/filebrowser/issues/554.
