### ISSUE TITLE
Multi architecture builds and manifests 

### ISSUE THREAD

**Issue by psyciknz** [abiosoft/caddy-docker#140]
Can i use the existing Dockerfile for generating binaries for arm/arm64 and x86?

It seems to hang on the git pull on the arm servers.

I'm hoping to use this guys framework https://lobradov.github.io/Building-docker-multiarch-images/ to pull the right alpine images so that I can build for all archs.

**Comment by abiosoft** [comment]
No you can't, because the images are based on amd64 alpine image.

**Comment by psyciknz** [comment]
Unless I rewrote your dockerfile for arm64v8.

Does that mean for the build function I need goos=Linux and goarch=arm64.

I’m trying that  anyway.

**Comment by abiosoft** [comment]
Oh, I misread your message. If it is simply to generate binaries, you can generate for any platform supported by Go including arm64 as indicated [here](https://github.com/abiosoft/caddy-docker/blob/master/BUILDER.md).

```
docker run --rm -v $(pwd):/install \
  -e PLUGINS=git,filemanager \
  -e GOARCH=arm64 \
  abiosoft/caddy:builder
```

**Comment by Maxiride** [comment]
@abiosoft, is [this](https://caddyserver.com/download) webpage the equivalent of `abiosoft/caddy:builder`?

**Comment by abiosoft** [comment]
@Maxiride Yes, that is official binaries from caddy's build servers. This image builds from source and leverages Docker. https://github.com/abiosoft/caddy-docker#license

**Comment by johnnyasantoss** [comment]
It still doesn't pull the correct image architecture. I tried on an armv7 and received an exec format error.
I believe it has something to do with the builder script which has fixed architecture on it. After cloning and removing [these lines](https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh#L45), I managed to make it work building the docker images locally.

**Comment by johnnyasantoss** [comment]
I don't know exactly how is the build process on dockerhub but I already seem a lot of images that have multi arch build there. eg. the images from https://www.linuxserver.io/
