### ISSUE TITLE
Update Docker Hub Version of Caddy

### ISSUE THREAD

**Issue by ejw9988** [abiosoft/caddy-docker#143]
Earlier this month Alpine Linux was updated from 3.8 to 3.8.1 for security fixes. Building the Caddy container from the Dockerfile will use the new version as expected. However, pulling the Caddy image from Docker Hub still pulls an image using 3.8.

Would it be possible to have the Docker Hub image updated to use the newer version of Alpine?

**Comment by abiosoft** [comment]
Yeah, sure. But it will only apply to `:latest` and not the tagged releases until the next version of Caddy is released.

**Comment by fungiboletus** [comment]
You could also rebuild and update the existing tags. I believe it's what Docker do on the official images.

**Comment by abiosoft** [comment]
Yes you can if you absolutely have to but ideally a tag should be a guarantee that it is not gonna change.
> You could also rebuild and update the existing tags. I believe it's what Docker do on the official images.

**Comment by abiosoft** [comment]
There is no `3.8.1` tag for Alpine, which means the current `3.8` tag has been updated. 
I have triggered new builds and the images should be using latest Alpine version any moment.

**Comment by teohhanhui** [comment]
There should be tags such as `abiosoft/caddy:1.0`. Refer to the official Docker images for a good example.

**Comment by abiosoft** [comment]
@teohhanhui https://hub.docker.com/r/abiosoft/caddy/tags

**Comment by teohhanhui** [comment]
@abiosoft I don't see a `1.0` tag.
