### ISSUE TITLE
Help with this wonderful image on Synology Diskstation

### ISSUE THREAD

**Issue by bonny1992** [abiosoft/caddy-docker#144]
Hello!
I wanted to use this awesome image on a Synology's DSM machine, but had no luck.
The latest version available for my sistem is the `Docker version 1.6.2, build a263667`, so I don't have the `--build-arg` functionality.

Since I need cloudflare dns plugin, I tried pulling the repo and editing the `php/Dockerfile-no-stats` file, but when I build the image it says `INFO[0011] Tag builder as builder not found in repository abiosoft/caddy`. I even tried pulling the images before then building with `--pull=false` but I didn't manage to make it work.

Can someone help me?
Thank you in advance!

**Comment by bonny1992** [comment]
Thanks to your help, I managed to make a fully working Caddy image!
However, some of the plugins I needed made the build to fail, I understand that this is not your fault of course.

Just to be sure, will your image work on a arm64v8 device?

**Comment by abiosoft** [comment]
Since Go supports it as seen [here](https://github.com/golang/go/wiki/MinimumRequirements#arm64), you should be able to generate a binary that works on an arm64 device. 

But you cannot use this docker image since it is based on amd64.

**Comment by abiosoft** [comment]
I'll be closing this as this is not really an issue with the image.
