### ISSUE TITLE
Current "Using git sources" example invalid

### ISSUE THREAD

**Issue by electerious** [abiosoft/caddy-docker#15]
It's not possible to use the current example command for "Using git sources" as git can't clone into a non-empty directory.

```
2016/07/27 14:42:02 cannot git clone into ., directory not empty
```

**Comment by abiosoft** [comment]
Very much possible. If your Caddyfile is not in `root`.

**Comment by abiosoft** [comment]
Oh sorry. I see what you mean. I will look for an alternative.

Thanks.

**Comment by abiosoft** [comment]
Fixed. 

Thanks.
