### ISSUE TITLE
Cloudflare plugin error 

### ISSUE THREAD

**Issue by rico93** [abiosoft/caddy-docker#151]
Hi 

I cant install caddy docker with cloudflare plugin. Here is the error output:

`docker build --build-arg     plugins=git,cloudflare     github.com/abiosoft/caddy-docker.git
Sending build context to Docker daemon  96.77kB
Step 1/22 : FROM abiosoft/caddy:builder as builder
 ---> 12cfe83bf812
Step 2/22 : ARG version="0.11.1"
 ---> Using cache
 ---> 8efbc8f8c54e
Step 3/22 : ARG plugins="git,cors,realip,expires,cache"
 ---> Using cache
 ---> 627591248e3c
Step 4/22 : RUN go get -v github.com/abiosoft/parent
 ---> Using cache
 ---> 16132d199b9f
Step 5/22 : RUN VERSION=${version} PLUGINS=${plugins} /bin/sh /usr/bin/builder.sh
 ---> Running in 5b67f2b467ab
Cloning into '/go/src/github.com/mholt/caddy'...
Note: checking out '6f580c6aa36c54c3e1c65b5c609550a8a2508e3e'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Switched to a new branch 'v0.11.1'
github.com/abiosoft/caddyplug (download)
github.com/abiosoft/errs (download)
github.com/fatih/color (download)
Fetching https://golang.org/x/sys/unix?go-get=1
Parsing meta tags from https://golang.org/x/sys/unix?go-get=1 (status code 200)
get "golang.org/x/sys/unix": found meta tag get.metaImport{Prefix:"golang.org/x/sys", VCS:"git", RepoRoot:"https://go.googlesource.com/sys"} at https://golang.org/x/sys/unix?go-get=1
get "golang.org/x/sys/unix": verifying non-authoritative meta tag
Fetching https://golang.org/x/sys?go-get=1
Parsing meta tags from https://golang.org/x/sys?go-get=1 (status code 200)
golang.org/x/sys (download)
github.com/abiosoft/caddyplug/internal
github.com/abiosoft/errs
github.com/fatih/color/vendor/github.com/mattn/go-isatty
github.com/fatih/color/vendor/github.com/mattn/go-colorable
github.com/fatih/color
golang.org/x/sys/unix
github.com/abiosoft/caddyplug/caddyplug
fetching missing dependencies: caddy, dnsproviders, hook.pluginloader
github.com/mholt/caddy/vendor/github.com/flynn/go-shlex
github.com/mholt/caddy/vendor/github.com/google/uuid
github.com/mholt/caddy/telemetry
github.com/mholt/caddy/caddyfile
github.com/mholt/caddy
Cloning into '/root/lib/caddy/gopath/src/github.com/caddyserver/dnsproviders'...
github.com/abiosoft/caddyplug (download)
github.com/abiosoft/caddyplug/internal
github.com/abiosoft/caddyplug
done fetching depedencies.

github.com/abiosoft/caddy-git (download)
github.com/abiosoft/caddy-git/gitos
github.com/mholt/caddy/vendor/github.com/flynn/go-shlex
github.com/mholt/caddy/vendor/github.com/google/uuid
github.com/mholt/caddy/telemetry
github.com/mholt/caddy/caddyfile
github.com/mholt/caddy
github.com/mholt/caddy/vendor/github.com/hashicorp/go-syslog
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/bifurcation/mint/syntax
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/golang.org/x/crypto/curve25519
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/golang.org/x/crypto/hkdf
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/bifurcation/mint
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/cheekybits/genny/generic
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/protocol
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/utils
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/congestion
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/hashicorp/golang-lru/simplelru
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/hashicorp/golang-lru
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/lucas-clemente/aes12
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/vendor/github.com/lucas-clemente/quic-go-certificates
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/qerr
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/crypto
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/handshake
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/wire
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/ackhandler
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/internal/flowcontrol
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go
github.com/mholt/caddy/vendor/golang.org/x/text/transform
github.com/mholt/caddy/vendor/golang.org/x/text/unicode/bidi
github.com/mholt/caddy/vendor/golang.org/x/text/secure/bidirule
github.com/mholt/caddy/vendor/golang.org/x/text/unicode/norm
github.com/mholt/caddy/vendor/golang.org/x/net/idna
github.com/mholt/caddy/vendor/golang.org/x/net/http/httpguts
github.com/mholt/caddy/vendor/golang.org/x/net/http2/hpack
github.com/mholt/caddy/vendor/golang.org/x/net/lex/httplex
github.com/mholt/caddy/vendor/golang.org/x/net/http2
github.com/mholt/caddy/vendor/github.com/lucas-clemente/quic-go/h2quic
github.com/mholt/caddy/caddyhttp/staticfiles
github.com/mholt/caddy/vendor/github.com/klauspost/cpuid
github.com/mholt/caddy/vendor/github.com/miekg/dns
github.com/mholt/caddy/vendor/golang.org/x/crypto/ocsp
github.com/mholt/caddy/vendor/golang.org/x/crypto/ed25519/internal/edwards25519
github.com/mholt/caddy/vendor/golang.org/x/crypto/ed25519
github.com/mholt/caddy/vendor/gopkg.in/square/go-jose.v2/cipher
github.com/mholt/caddy/vendor/gopkg.in/square/go-jose.v2/json
github.com/mholt/caddy/vendor/gopkg.in/square/go-jose.v2
github.com/mholt/caddy/vendor/github.com/xenolf/lego/acmev2
github.com/mholt/caddy/caddytls
github.com/mholt/caddy/vendor/github.com/russross/blackfriday
github.com/mholt/caddy/vendor/gopkg.in/natefinch/lumberjack.v2
github.com/mholt/caddy/caddyhttp/httpserver
github.com/abiosoft/caddy-git
github.com/caddyserver/dnsproviders (download)
github.com/xenolf/lego (download)
github.com/xenolf/lego/vendor/github.com/pkg/errors
github.com/xenolf/lego/vendor/golang.org/x/time/rate
github.com/xenolf/lego/vendor/github.com/cloudflare/cloudflare-go
github.com/xenolf/lego/vendor/golang.org/x/crypto/ed25519/internal/edwards25519
github.com/xenolf/lego/vendor/golang.org/x/crypto/ed25519
github.com/xenolf/lego/vendor/golang.org/x/net/bpf
github.com/xenolf/lego/vendor/golang.org/x/net/internal/iana
github.com/xenolf/lego/vendor/golang.org/x/net/internal/socket
github.com/xenolf/lego/vendor/golang.org/x/net/ipv4
github.com/xenolf/lego/vendor/golang.org/x/net/ipv6
github.com/xenolf/lego/vendor/golang.org/x/sys/unix
github.com/xenolf/lego/vendor/github.com/miekg/dns
github.com/xenolf/lego/acme
github.com/xenolf/lego/acme/api/internal/sender
github.com/xenolf/lego/acme/api/internal/nonces
github.com/xenolf/lego/vendor/golang.org/x/crypto/pbkdf2
github.com/xenolf/lego/vendor/gopkg.in/square/go-jose.v2/cipher
github.com/xenolf/lego/vendor/gopkg.in/square/go-jose.v2/json
github.com/xenolf/lego/vendor/gopkg.in/square/go-jose.v2
github.com/xenolf/lego/acme/api/internal/secure
github.com/xenolf/lego/vendor/golang.org/x/crypto/ocsp
github.com/xenolf/lego/certcrypto
github.com/xenolf/lego/log
github.com/xenolf/lego/acme/api
github.com/xenolf/lego/challenge
github.com/xenolf/lego/platform/wait
github.com/xenolf/lego/challenge/dns01
github.com/xenolf/lego/platform/config/env
github.com/xenolf/lego/providers/dns/cloudflare
github.com/caddyserver/dnsproviders/cloudflare
# github.com/caddyserver/dnsproviders/cloudflare
../../caddyserver/dnsproviders/cloudflare/cloudflare.go:27:10: undefined: "github.com/xenolf/lego/providers/dns/cloudflare".NewDNSProviderCredentials
Cloning into '/go/src/github.com/caddyserver/builds'...
# github.com/caddyserver/dnsproviders/cloudflare
../../../caddyserver/dnsproviders/cloudflare/cloudflare.go:27:10: undefined: "github.com/xenolf/lego/providers/dns/cloudflare".NewDNSProviderCredentials
2018/12/07 09:50:29 exit status 2
exit status 1
`

**Comment by romcheck** [comment]
same here with gandiv5 plugin:
https://github.com/mholt/caddy/issues/2385

**Comment by grugnog** [comment]
https://github.com/mholt/caddy/blob/master/vendor/manifest#L170 is pointing to the lego commit prior to this one, so the issue is that builder (at https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh#L34 maybe) is not using the vendor directory.

**Comment by abiosoft** [comment]
This has been fixed. `docker rmi abiosoft/caddy:builder` and try again.
