### ISSUE TITLE
Custom DNS plugins?

### ISSUE THREAD

**Issue by manad777** [abiosoft/caddy-docker#159]
For custom plugins, the README gives the example "plugins=filemanager,git,linode". However I don't see these 3 plugins anywhere on Caddyserver's download page. They have http.git, tls.dns.linode, and no mention of filemanager.

Also, wouldn't it be better to include all plugins by default? Or would the build times become unacceptable?

**Comment by dajeffers** [comment]
Your issue's been hanging open for a while, so I'll assume you haven't gotten an answer yet.

Filemanager was deprecated in favor of http.filebrowser, you'll find information about it on the [Caddy forum](https://caddy.community/t/new-old-plugin-http-filebrowser/5103).

Including all plugins by default would make the container (and application itself) far too large, caddy is relatively lightweight and the efficiency (while maintaining extensibility) is sort of a feature that I don't think most would want to be rid of.

**Comment by abiosoft** [comment]
This image bundles [some popular plugins](https://github.com/abiosoft/caddy-docker#caddy). 

You can easily extend the image via a custom `Dockerfile` or use the docker based [builder](https://github.com/abiosoft/caddy-docker/blob/master/BUILDER.md).
