### ISSUE TITLE
composer functionality obstructed by VOLUME

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#16]
This took me sadly some time to figure out the issue. `VOLUME` I believe prevents composer from writing out the dependencies to `/srv/`

    FROM abiosoft/caddy:php
    RUN touch /srv/foobar
    RUN ls /srv/

And it needs to be there for a typical `require 'vendor/autoload.php';` pattern.

BUT when I try `composer global require aws/aws-sdk-php` it installs to `/root/.composer/` and I get permission denied trying to use that directory.

**Comment by emilbayes** [comment]
Yeah, it don't know what the intention with composer was in this image, given you can't build a image on top with all your dependencies installed

**Comment by abiosoft** [comment]
I'm trying to see if there is any side effects to removing `VOLUME /srv`. Before, it was `RUN mkdir /srv`.

**Comment by emilbayes** [comment]
I think there might be issues, since you can link exposed volumes from other containers: https://docs.docker.com/engine/tutorials/dockervolumes/#/creating-and-mounting-a-data-volume-container

I'm not entirely sure though, and I don't see the point of mounting the volume, if you haven't populated it yourself, in which case it should be available anyway (to my understanding)

**Comment by abiosoft** [comment]
@kaihendry are you saying that you get errors even after the container is running ?

**Comment by kaihendry** [comment]
@abiosoft no... ?

Sorry I haven't done the pull request, but the change is trivial. Remove VOLUME. I did test it successfully over here: https://github.com/kaihendry/docker-tutorial/blob/master/advanced/composer/Dockerfile

**Comment by abiosoft** [comment]
Yeah I know its trivial. Since you discovered the issue, I thought you'd like to.

After a bit of research, I do not see any real downsides to removing `VOLUME`. You can always mount volume when starting the container if required. So I'll be removing the line.

Thanks.

**Comment by abiosoft** [comment]
Done
