### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by Imperial-Guard** [abiosoft/caddy-docker#173]
Activating privacy features... 2019/03/25 12:18:28 [INFO][FileStorage:/etc/caddycerts] Started certificate maintenance routine
2019/03/25 12:18:28 get Agreement URL: Get https://acme-v02.api.letsencrypt.org/directory: x509: certificate signed by unknown authority
exit status 1

Any thoughts? 

I let the docker run with the following command:

docker run --init -d --name="caddy" --restart always -v "caddy_config:/root/.caddy" -v "caddy_config:/srv" -v "caddy_config:/etc" -e "CADDYPATH=/etc/caddycerts" -e ACME_AGREE=true -v caddy_config:/etc/caddycerts -p 80:80 -p 443:443 abiosoft/caddy

**Comment by werty1st** [comment]
If you build you own image with custom addons you may need to add:

`RUN apk update && apk add ca-certificates && rm -rf /var/cache/apk/*
`

**Comment by colachg** [comment]
@werty1st Thanks, it works!

**Comment by abiosoft** [comment]
Fixed with https://github.com/abiosoft/caddy-docker/pull/202

**Comment by Askill** [comment]
I am getting the same error with the latest image
