### ISSUE TITLE
Call to undefined function simplexml_load_string()

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#175]
How do I support XML with your image?

https://stackoverflow.com/questions/31206186/call-to-undefined-function-simplexml-load-string

Use your [image](https://github.com/abiosoft/caddy-docker/blob/php/Dockerfile) as a base?

Thank you!

**Comment by kaihendry** [comment]
I quickly created a new image https://hub.docker.com/r/uneet/caddyphp

```
FROM abiosoft/caddy:php

RUN apk add --update php-simplexml

ENTRYPOINT ["/usr/bin/caddy"]
CMD ["--conf", "/etc/Caddyfile"]
```

**Comment by abiosoft** [comment]
I'll add `php-simplexml` to the list of installed packages.

Thanks.

**Comment by kaihendry** [comment]
Have you done this? https://github.com/abiosoft/caddy-docker/blob/php/Dockerfile

**Comment by abiosoft** [comment]
I've stopped using the php branch, but rather a php subdirectory in the master branch.
Yeah, I added it. https://github.com/abiosoft/caddy-docker/blob/master/php/Dockerfile#L50.
