### ISSUE TITLE
caddyserver/builds repo is missing

### ISSUE THREAD

**Issue by victor141516** [abiosoft/caddy-docker#177]
I just tried to buid caddy using the following command:

`> docker build -t my-caddy --build-arg plugins=prometheus github.com/abiosoft/caddy-docker.git`

And at some point it fails with:

```
Cloning into '/go/src/github.com/caddyserver/builds'...
fatal: could not read Username for 'https://github.com': No such device or address
```

Here is the line: https://github.com/abiosoft/caddy-docker/blob/master/builder/builder.sh#L49

And the linking repo is missing: https://github.com/caddyserver/builds

**Comment by abiosoft** [comment]
Yeah, it was a decision made in the past few days. I've already fixed it locally, will push the update any moment.

**Comment by abiosoft** [comment]
Going forward `caddy -version` for versions prior to 1.0.0 will no longer reflect the version.

**Comment by abiosoft** [comment]
Pushed. Should be live within the next hour when Docker Cloud CI finishes.

**Comment by olegstepura** [comment]
The issue persists somehow:
```bash
docker build -t my-caddy --build-arg plugins=prometheus github.com/abiosoft/caddy-docker.git
```

```
...
fetching missing dependencies: caddy, dnsproviders, hook.pluginloader
chdir /root/lib/caddy/gopath/src/github.com/mholt/caddy: no such file or directory
Cloning into '/go/src/github.com/caddyserver/builds'...
fatal: could not read Username for 'https://github.com': No such device or address
stat build.go: no such file or directory
```

**Comment by abiosoft** [comment]
@olegstepura try `docker rmi abiosoft/caddy:builder` and try again.

**Comment by olegstepura** [comment]
@abiosoft Thanks! This worked. Seems like it's a known issues that the builder container is cached and not updated? Maybe it's worth updating readme?
