### ISSUE TITLE
WARNING: File descriptor limit 1024 is too low for production servers. At least 8192 is recommended. Fix with `ulimit -n 8192`.

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#178]
How do I fix this ulimit issue, or can this warning be ignored?

Thank you!

**Comment by abiosoft** [comment]
What version of the docker image are you running? 
What distro is your server running?

I'll be closing this since it is not an issue with both docker image and caddy, rather your server configuration. But we can continue the discussion here.

**Comment by kaihendry** [comment]
Latest abiosoft/caddy:php on AWS ECS.

```
docker run -d --rm \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    -v $(pwd)/src:/srv \
    -v $HOME/.caddy:/root/.caddy \
    -v $HOME/php.ini:/etc/php7/php.ini \
    -p 80:80 -p 443:443 -p 2015:2015 \
    abiosoft/caddy:php

```
