### ISSUE TITLE
php variant timeouts

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#179]
30/Apr/2019:01:51:31 +0000 [ERROR 504 /foobar.php] read tcp 127.0.0.1:49154->127.0.0.1:9000: i/o timeout

Any ideas to what might be causing this or how to debug it?

Thank you!

**Comment by abiosoft** [comment]
You may want to increase the `read_timeout` configuration. https://caddyserver.com/docs/fastcgi.

**Comment by kaihendry** [comment]
Thank you! I think that works. However, I need to better track timeouts. Any ideas how to improve:

    30/Apr/2019:08:02:53 +0000 [ERROR 504 /foobar.php] read tcp 127.0.0.1:50380->127.0.0.1:9000: i/o timeout

With the timings?

**Comment by kaihendry** [comment]
read_timeout works
