### ISSUE TITLE
Templating breaks mime type of other files (only on this build, not with official Caddy)

### ISSUE THREAD

**Issue by renaudguerin** [abiosoft/caddy-docker#182]
Enabling `templates` for .html (or just with default settings) breaks the mime types of JSON files in the paths it is enabled for. They're all served as `text/plain; charset=utf-8`

Plot twist : I can't reproduce this with Caddy 1.0.0 on my Mac, I only have this problem with this `abiosoft/caddy-docker` Docker image (so, I don't know if it's a Linux specific problem or due to the way it's built)

Repro steps: very simple Caddyfile with 
```
:2015
templates
mime .json application/json
```

- ` curl -I localhost:2016/` (templated index.html) correctly returns  `Content-Type: text/html; charset=utf-8`
- ` curl -I localhost:2016/config.json` (plain JSON file) **wrongly** returns  `Content-Type: text/plain; charset=utf-8`

What I've tried:
- Rebuilding the container without any plugins, to match the vanilla Caddy I'm using on Mac (using `docker build --build-arg plugins="" github.com/abiosoft/caddy-docker.git` and they now both output the exact same version and plugins). **Didn't work.**
- Forcing/not forcing the type with the `mime` directive. **Didn't work.**
- Explicitly setting `templates / .html` and using the long form with `path` / `ext` / `between`. **Didn't work.**
- Restricting `templates` to a subpath like this : `templates /subdir .html`. **This works** : JSON files outside of that path are now served correctly. **But I can't use that** because I need my index templated !

Any help greatly appreciated !

**Comment by renaudguerin** [comment]
I finally have a workaround : the only thing that worked was adding `RUN apk --no-cache add mailcap` to the Dockerfile. This was probably the only difference between my Linux/Docker environment and the Mac one.

Again, forcing the type with the `mime` directive was **not** enough in my case ! Maybe this code path is bypassed when `templates` is enabled and it falls back to the default case that relies on a `mailcap` file to determine the type ?

**Comment by abiosoft** [comment]
I can add `mailcap` to the docker image if that fixes it.

**Comment by renaudguerin** [comment]
I still believe this is a bug, but adding `mailcap` is definitely a workaround !

**Comment by abiosoft** [comment]
Fixed with https://github.com/abiosoft/caddy-docker/pull/202
