### ISSUE TITLE
using "docker run" ... unknown dns provider

### ISSUE THREAD

**Issue by hiqbn** [abiosoft/caddy-docker#183]
docker run -it -e CLOUDFLARE_EMAIL=something@example.com -e CLOUDFLARE_API_KEY=123456789 --name caddy -h caddy -p 2015:2015 -p 443:443 -v $(pwd)/Caddyfile:/etc/Caddyfile abiosoft/caddy

I need to run it as docker run instead of the docker compose method. can you pls help? 

because i'm stuck at 

           /etc/Caddyfile:6 - Error during parsing: Unknown DNS provider by name 'cloudflare'

nice software by the way and thanks in advance.

is this correct for example.com and wildcard subdomain for example.com?

Caddyfile
-----------------------
```

example.com *.example.com {
    proxy / http://10.1.0.123:80
    tls myemail@example.com

    tls {
        dns cloudflare
    }
}

```

**Comment by abiosoft** [comment]
cloudflare is not bundled with the default image.

Build your custom docker image and use it instead. You can include other plugins.
```
docker build -t mycaddy --build-arg \
    plugins=git,cloudflare \
    github.com/abiosoft/caddy-docker.git
```
Then run it
```
docker run -it -e CLOUDFLARE_EMAIL=something@example.com -e CLOUDFLARE_API_KEY=123456789 --name caddy -h caddy -p 2015:2015 -p 443:443 -v $(pwd)/Caddyfile:/etc/Caddyfile mycaddy
```
