### ISSUE TITLE
managed to get into the docker instance. thanks but it doesnt seem to autorun.

### ISSUE THREAD

**Issue by hiqbn** [abiosoft/caddy-docker#184]
i'm inside the container by doing 
docker exec -it caddy /bin/sh
there's no process inside.

what command should i type for it to run?

**Comment by abiosoft** [comment]
What command are you using to start the container?

I'll be closing this as it is not an issue with Caddy or the image. However, the discussion can continue.

**Comment by hiqbn** [comment]
docker run -it -e CLOUDFLARE_EMAIL=email -e CLOUDFLARE_API_KEY=12345678 -h caddy --name caddy -p 2015:2015 -p 443:443 -v $(pwd)/Caddyfile:/etc/Caddyfile abiosoft/caddy:builder /bin/sh

i have no idea why it doesnt autorun but i'm inside the container. pls inform how to run the caddy process inside as once inside, there are no processes other than 2 system process of linux

**Comment by abiosoft** [comment]
`abiosoft/caddy:builder` is for generating caddy binaries.
`abiosoft/caddy` (or your custom image) is what you should run.

**Comment by hiqbn** [comment]
when i ran the abiosoft/caddy, it says 
Unknown DNS provider by name 'cloudflare' error. I've managed to generate the image

REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              b0b3e97b2343        18 hours ago        466MB
abiosoft/caddy      latest              2a1f4da4f9a6        2 weeks ago         46.3MB
abiosoft/caddy      builder             d13c525ed8b9        2 weeks ago         464MB

how do i run this?

**Comment by abiosoft** [comment]
Use the image tag `b0b3e97b2343`. You could've used docker build -t `custom_tag` to have a custom tag.
```
docker run -it -e CLOUDFLARE_EMAIL=email -e CLOUDFLARE_API_KEY=12345678 -h caddy --name caddy -p 2015:2015 -p 443:443 -v $(pwd)/Caddyfile:/etc/Caddyfile b0b3e97b2343
```

**Comment by hiqbn** [comment]
CONTAINER ID        IMAGE               COMMAND                  CREATED              STATUS                    PORTS               NAMES
2895f104c1a9        b0b3                "/bin/sh /usr/bin/bu…"   About a minute ago   Exited (1) 1 second ago                       caddy

it will never be started with 
docker start caddy

i did however did the /bin/sh at the end of the container above and can ssh into it BUT like i said, there's no default running processes inside. how do i run it?

**Comment by hiqbn** [comment]
any feedback on this?

**Comment by hiqbn** [comment]
can you pls help?

**Comment by abiosoft** [comment]
There are issues with some plugins (including cloudflare) at the moment. It is not building with Caddy 1.0 due to go modules requirement.

You can follow the following steps to get Caddy running.
```
plugins=git,cors # you can have other plugins, just comma separate them
docker build --build-arg plugins=$plugin -t mycaddy github.com/abiosoft/caddy-docker.git
docker run -it --rm --name caddy -p 2015:2015 -p 443:443 -v $(pwd)/Caddyfile:/etc/Caddyfile mycaddy
```

It that is not successful, you can check what went wrong with `docker logs -f mycaddy`.

**Comment by hiqbn** [comment]
can u provide the code for cloudflare only for me to test? the instructions for setting up cloudflare
