### ISSUE TITLE
Problems building

### ISSUE THREAD

**Issue by sn00pster** [abiosoft/caddy-docker#186]
I'm having real trouble building a caddy image, both locally (on Ubuntu) and using dockerhub.

I'm getting to the "building caddy" stage and then I'm randomly getting:

go: finding [module name]
go: error loading module requirements
error at 'building caddy'

It randomly stops on different modules, you see a noticable pause on finding and then the error appears, so it's like it's timed out trying to find the module and doesn't retry, just fails.

I cannot for the life of me get caddy to build.

Help!

**Comment by sn00pster** [comment]
This only seems to affect version 1.0.0, if I change the Dockerfile to use 0.11.5 then it builds correctly with the cloudflare plugin, switching back to 1.0.0 breaks it.

**Comment by abiosoft** [comment]
It's similar to this https://github.com/abiosoft/caddy-docker/issues/185. Not all plugins support Go modules yet, which is a requirement for caddy 1.0.0.
