### ISSUE TITLE
Timezone setting

### ISSUE THREAD

**Issue by pointbre** [abiosoft/caddy-docker#189]
Hi, 

In order to set the proper timezone with Caddy, I've made a change to Dockerfile like the following:

```
...
# install process wrapper
COPY --from=builder /go/bin/parent /bin/parent

# Add timezone
RUN apk add tzdata

ENTRYPOINT ["/bin/parent", "caddy"]
...
```

Docker image building went ok.

When running the caddy-docker image, I've set `TZ=Pacific/Auckland` and I could see my local time in Caddy's access log. Please make the change so that everybody can set timezone.

Thanks

**Comment by abiosoft** [comment]
@pointbre thanks. You mean you only had to set the `TZ` env var?

That is a straightforward change. I'll add it to the container.

**Comment by pointbre** [comment]
`RUN apk add tzdata` to Dockerfile and `TZ` env car to container, that's all.

**Comment by FinalFrag** [comment]
Another option is to add this to your docker-compose.yml when using the container
`volumes:
    - "/etc/localtime:/etc/localtime:ro"
    - "/etc/timezone:/etc/timezone:ro"`

**Comment by nurtext** [comment]
Snippet I'm using in almost all my alpine containers:

```
# Timezone
ENV TIMEZONE Europe/Berlin

# Install timezone data and setup timezone
RUN apk --update add --no-cache --virtual .tz-deps tzdata \
    && cp /usr/share/zoneinfo/$TIMEZONE /etc/localtime \
    && echo $TIMEZONE > /etc/timezone \
    && apk del .tz-deps
```

**Comment by abiosoft** [comment]
Fixed with https://github.com/abiosoft/caddy-docker/pull/202

**Comment by DoTheEvo** [comment]
Was tzdata removed?
cuz TZ variable does not work for me.
if I install it manually it works

![img](https://i.imgur.com/XP8xBSK.png)
