### ISSUE TITLE
ADD vs COPY

### ISSUE THREAD

**Issue by MatthewVance** [abiosoft/caddy-docker#19]
Is there a reason why this uses the `ADD` instruction over `COPY` for the Caddyfile and index.html files? From what I understand, `COPY` is generally preferred.

- https://docs.docker.com/engine/userguide/eng-image/dockerfile_best-practices/#/add-or-copy
- https://www.ctl.io/developers/blog/post/dockerfile-add-vs-copy/

I can create a pull request if you want.

**Comment by abiosoft** [comment]
I'd appreciate a PR.

Thanks.
