### ISSUE TITLE
Consider adding /etc/mime.types to Docker image

### ISSUE THREAD

**Issue by NicolasLM** [abiosoft/caddy-docker#193]
I'm hitting a bug that I don't fully grasp yet: when a `304` response is being served it contains no `Content-Type` header. As I set `X-Content-Type-Options: nosniff` browsers refuse to use the resource (css, js...) and the page is displayed unstyled.

Since I use Caddy and the plugin `cache` I'm not exactly sure where the problem comes from but it seems that [adding the package `mailcap` to the docker build](https://github.com/mholt/caddy/issues/1050#issuecomment-484013773) fixes the problem. This package contains `/etc/mime.types` that Caddy can use to map files to the correct `Content-Type`.

**Comment by NicolasLM** [comment]
After investigating, my original problem is not related to `/etc/mime.types`. However adding this file would still solve the issue I linked, so maybe it's worth keeping this one open.

**Comment by abiosoft** [comment]
Fixed with https://github.com/abiosoft/caddy-docker/pull/202
