### ISSUE TITLE
Custom builds no longer work

### ISSUE THREAD

**Issue by rochdev** [abiosoft/caddy-docker#194]
It is no longer possible to build a custom image with (or without) plugins since the command throws an error:

```
fatal: could not read Username for 'https://github.com': No such device or address
stat build.go: no such file or directory
```

This was using this very simple command:

```
docker build \
  -t rochdev/caddy-proxy \
  github.com/abiosoft/caddy-docker.git
```

**Comment by abiosoft** [comment]
Run `docker rmi abiosoft/caddy:builder` and try again.

**Comment by rochdev** [comment]
That solved this issue. I am getting a different error now but only with custom plugins. I'll open a different issue for that if I can't figure it out.

Thanks!

**Comment by rochdev** [comment]
The new error turned out to be because of https://github.com/abiosoft/caddy-docker/issues/185
