### ISSUE TITLE
cannot add supervisor plugin

### ISSUE THREAD

**Issue by schmurfy** [abiosoft/caddy-docker#208]
Hello, 
I wanted to build an image with `https://github.com/lucaslorentz/caddy-supervisor` but I cannot find how, I tried using `supervisor` and `caddy-supervisor` but none of those worked, it shows that `import path "" is invalid`

where is the list of useable plugins and the correct names ?

**Comment by abiosoft** [comment]
Yeah, support for supervisor type plugins is missing. I'll add it when I find time.

**Comment by schmurfy** [comment]
I can have a look if you point me toward the right direction :)
