### ISSUE TITLE
Reduce image size

### ISSUE THREAD

**Issue by MatthewVance** [abiosoft/caddy-docker#22]
Do you think it's worth combining the two `RUN` commands into a single one to reduce the number of layers? Also, it might be good to add a command near the end to remove the packages only needed for building the image (curl and tar). It'd probably look something like:

```console
apk add --update --no-cache --virtual .build-deps tar curl \
&& apk add --update --no-cache openssh-client git \
...
apk del .build-deps 
```

Also, why is openssh-client package needed?

**Comment by abiosoft** [comment]
openssh-client package is needed because of private git repositories. The image includes the git plugin.

**Comment by abiosoft** [comment]
Thanks for this suggestion. Yeah, the smaller the image, the better.

**Comment by abiosoft** [comment]
After another look, the size gain is not much and I do not think it is worthy sacrificing the readability of the Dockerfiles for it. 

I'd be willing to if we will be gaining tens of MegaBytes.

**Comment by MatthewVance** [comment]
Fair enough. Thanks for considering.

**Comment by MatthewVance** [comment]
Thanks for letting me know why the openssh-client was needed. It never thought about it being needed by private git repos.
