### ISSUE TITLE
ipfilter database

### ISSUE THREAD

**Issue by MatthewVance** [abiosoft/caddy-docker#23]
Since the [ipfilter addon](https://caddyserver.com/docs/ipfilter) is included by default, should the GeoLite2 Country database be copied into the image so filtering clients based on countries codes would be possible? I guess the other option would be to include instructions about how to add the database manually. One way would be to build a custom image based from this one which copies it to the newly created image. Adding it as a volume at run time might also work.

**Comment by abiosoft** [comment]
I think I'll remove the ipfilter addon. I added it based on some users' suggestion but unlike git, I am not maintaining ipfilter.

**Comment by abiosoft** [comment]
Users can extend the image and include ipfilter.

**Comment by abiosoft** [comment]
ipfilter is no longer bundled by default.

**Comment by abiosoft** [comment]
ipfilter is no longer bundled by default.
