### ISSUE TITLE
Build error: cannot find module providing package crypto/ed25519

### ISSUE THREAD

**Issue by gucki** [abiosoft/caddy-docker#238]
Building the image fails with "build caddy: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519".

**Comment by gucki** [comment]
The problem is the builder uses golang 1.12. With 1.13 it works!

**Comment by MatheusSandre** [comment]
i have the same problem

**Comment by omonimus1** [comment]
I have the same problem in version 1.15.10
