### ISSUE TITLE
Add images for Caddy version 2 beta

### ISSUE THREAD

**Issue by h1nk** [abiosoft/caddy-docker#239]
Issue title describes it all really.

**Comment by Jacobite89** [comment]
Hi everyone,
I had build a Caddy 2 Docker Image. If you want, be free to test it.

Github: [Jacobite89/caddy-docker]( https://github.com/Jacobite89/caddy-docker)
Docker Hub: [jacobite589/caddy](https://hub.docker.com/r/jacobite589/caddy/tags)

For now the Container is unrooted, a healtheck is running and a seperate Image with a small php set is available.

**Comment by gotson** [comment]
Seems there are official images : https://hub.docker.com/r/caddy/caddy

**Comment by hartwork** [comment]
New link seems to be https://hub.docker.com/_/caddy .
@h1nk could you drop the `beta` from the issue title? Thanks!

**Comment by h1nk** [comment]
@hartwork seeing as there are officially maintained Docker Hub images now I'm just gonna close this one out
