### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by andrewbanchich** [abiosoft/caddy-docker#24]
@abiosoft Would you be able to provide some example `docker-compose.yml` files for this and the official WordPress/MariaDB docker images? Being new to Docker, I'm having some trouble configuring it to get it to work.

**Comment by abiosoft** [comment]
Considering this is not an **issue**, I will be closing this.

However, share your progress and let me see how I can help. 

I will consider creating an examples directory in this repository.
