### ISSUE TITLE
Caddy does not have permission to create its home directory

### ISSUE THREAD

**Issue by samwalls** [abiosoft/caddy-docker#25]
I'm very new to both docker and caddy so this could be something wonky in my configuration. I can get the docker container to work without any custom caddyfile or source files, i.e. if I `curl localhost:2015` I get the html from the generated page. However, when I add a custom caddyfile the docker instance dies.

Some details about my server:

- Ubuntu 14.04

`docker version`
```
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 05:22:43 2016
 OS/Arch:      linux/amd64
```

This is my Caddyfile:
```
[my-domain]:8080
root /srv
log ../access.log
```

the domain itself _does_ point to the server in question.

When I try to run this (whether as root or not): `docker run -d -v $(pwd)/srv:/srv -v $(pwd)/etc/Caddyfile:/etc/Caddyfile abiosoft/caddy`

the container instantly closes and the log for the container is as follows:

```
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
2016/09/12 23:42:56 could not save user: mkdir /home/caddy: permission denied
Email address:
```

I can also confirm that I have put my own user in the docker group, I also set the group of the caddyfile and everything in `srv` to `docker`.

**Comment by abiosoft** [comment]
Hi, thanks for reporting this. I have fixed the issue.

Can you pull the docker image and try again ?

Also, `log ../access.log` is not going to work because the current user is not a root user. Why not just `log access.log` or `log /home/caddy/access.log` ?

Feel free to reopen if you still get the error message.

**Comment by samwalls** [comment]
Thank you for your response. The reason I use `../access.log` is because that is what is in the example (from caddy itself) and I didn't consider that this would have to work differently in docker.

By "pull the docker image", do you mean to just use `docker run ... abiosoft/caddy` again?

**Comment by samwalls** [comment]
Never mind, I managed to pull the new image. It would appear to have fixed the previous problem, but presents a new one in its place:

```
Activating privacy features...
Your sites will be served over HTTPS automatically using Let's Encrypt.
By continuing, you agree to the Let's Encrypt Subscriber Agreement at:
  https://acme-v01.api.letsencrypt.org/terms
Please enter your email address so you can recover your account if needed.
You can leave it blank, but you'll lose the ability to recover your account.
2016/09/13 12:02:30 [my-domain] failed to get certificate: [my-domain] error presenting token: Could not start HTTP server for challenge -> listen tcp :80: bind: permission denied
Email address: 
```
I thought that the permission denied to host on port 80 might be an issue where you need to be the root, but I also get this when using `docker run ...` as root, perhaps caddy needs this permission as well?

**Comment by abiosoft** [comment]
By pulling the image again, I mean this.
```
docker pull abiosoft/caddy
```

I have not been able to reproduce this. It binds perfectly to port 80.

**Comment by abiosoft** [comment]
FYI, since current `:latest` and `:0.9.3`, no more unprivileged `caddy` user and there should be no write permission issues anymore. I had to revert the user update.
