### ISSUE TITLE
Caddy + WordPress write permissions

### ISSUE THREAD

**Issue by andrewbanchich** [abiosoft/caddy-docker#26]
I configured Docker Compose to set up Caddy, WordPress, and MySQL. The site works fine, except when I upload a theme it says "Unable to create directory wp-content/uploads/2016/09. Is its parent directory writable by the server?".

I am thinking that this is because I am using the PHP version of Caddy and that that is trying to add the theme files to the WordPress container by way of a mounted volume, and that WordPress's container doesn't recognize the Caddy container as the www-data user. Is that correct? How do I fix this?

[Here is my setup](https://gitlab.com/andrewbanchich/docker-configs/tree/master/wordpress/caddy-mysql).

Thanks

**Comment by abiosoft** [comment]
This is because I dropped the user in the container from `root` to less-privileged `caddy` recently to follow best practices.

 I'm trying your setup now to reproduce it and will respond when I find a fix.

Now I'm wondering if I should've just left it as `root` instead of following "best practices". I've had to deal with many permission issues recently. I hope this will be the last.

**Comment by abiosoft** [comment]
This is redundant as the wordpress docker image already bundled apache.

If you want to use Caddy mainly for automatic https, a reverse proxy is all you need Caddy for.

To fix the permission issues, the caddy image is configured to have source files in `/srv` i.e. we need to put the wordpress source files in `/srv/`.

**Comment by andrewbanchich** [comment]
@abiosoft I'm new to Docker, but I thought that shared volumes couldn't be bound to specific directories. For example, I used `volumes_from:  - wordpress` to bind the `/var/www/html` directory to the Caddy container. How would I go about specifying that I want to bind it to `/srv/` instead?

**Comment by abiosoft** [comment]
I've fixed it and it works now. Check it here https://gist.github.com/abiosoft/92fa7575d255ef49ec614485e78ed3c5.

What I did is to use the fpm variant of the wordpress image `wordpress:fpm` which included php-fpm only; then use plain caddy `abiosoft/caddy` instead of `abiosoft/caddy:php`. I also made some changes to the volume paths.

**Comment by andrewbanchich** [comment]
@abiosoft Thanks! I'll try that out. A couple questions though:

1. So the approach you suggested regarding php.ini would just be for me to use 

`volumes:`
`    - "/var/www/html"`
`    - "./php.ini:/etc/php5/conf.d/php.ini"`

instead of

`volumes:`
`    - "/var/www/html"`
`    - "./php.ini:/usr/local/etc/php/php.ini"`

?

2. I'm totally new to setting up a reverse proxy server, and no matter what configs I try with Docker I can't get it to work. I am pretty sure I'm just misunderstanding some simple thing. Could you provide an example Caddyfile/docker-config file that would work so that Caddy can do that?

**Comment by abiosoft** [comment]
The volume is `/usr/src/wordpress` as you can confirm from the image's Dockerfile [here](https://github.com/docker-library/wordpress/blob/81d061a68456cc14fcebb88a17b61d600eac30e9/fpm/Dockerfile#L29). 

Compare the entire Caddyfile and docker-compose.yml files. The changes are more than just volumes though almost the same with yours.

**Comment by andrewbanchich** [comment]
@abiosoft I'll check them out. I'm just interested in why the WP container has all the WP files in both locations. If you run `docker -it exec wordpress bash` it sends you to the `/var/www/html` directory which contains all the same files as `/usr/src/wordpress`.

**Comment by abiosoft** [comment]
Oh interesting. I didn't notice that.

**Comment by andrewbanchich** [comment]
@abiosoft I tried the new setup you linked to and it gives me a fatal error when I add the database info. Have you tried using it?

Also, do I enter `db:3306` in the database host? That's the only way I can get it to get to the next step.

**Comment by abiosoft** [comment]
Yes. I tried it and it worked.

What database info did you add and what fatal error did you get ?

**Comment by andrewbanchich** [comment]
@abiosoft `Fatal error: Uncaught exception 'phpmailerException' with message 'Invalid address: wordpress@' in /usr/src/wordpress/wp-includes/class-phpmailer.php:946 Stack trace: #0 /usr/src/wordpress/wp-includes/pluggable.php(352): PHPMailer->setFrom('wordpress@', 'WordPress', false) #1 /usr/src/wordpress/wp-admin/includes/upgrade.php(392): wp_mail('andrewbanchich@...', 'New WordPress S...', 'Your new WordPr...') #2 /usr/src/wordpress/wp-admin/includes/upgrade.php(95): wp_new_blog_notification('Sharon's Englis...', 'http://sharonse...', 1, 'The password yo...') #3 /usr/src/wordpress/wp-admin/install.php(367): wp_install('Sharon's Englis...', 'Andrew', 'andrewbanchich@...', 1, '', MYPASSWORD', 'en_US') #4 {main} thrown in /usr/src/wordpress/wp-includes/class-phpmailer.php on line 946`

**Comment by abiosoft** [comment]
Oh, that one. If you refresh the page you'll see that it is set up. I saw that as well.

I think it happens when you are in an environment that can not send email. Not sure why it is such a fatal error.

**Comment by andrewbanchich** [comment]
Gotcha, thanks!

**Comment by abiosoft** [comment]
FYI, since current `:latest` and `:0.9.3`, no more unprivileged `caddy` user and there should be no write permission issues anymore. I had to revert the user update.
