### ISSUE TITLE
SSL broke on a live server after the `be00e81` commit

### ISSUE THREAD

**Issue by pavlo** [abiosoft/caddy-docker#29]
Hey guys, 

The commit/change below broke the SSL on my live server all of the sudden. I'd want to inquiry about a couple of things in this regard -

1. What's your policy in regard to making changes that break stuff like this? Meaning is there a release notes document, a change log, release schedule or something I would subscribe to to be aware of coming changes?
2. Would you recommend not use "latest" image and freeze the one I am happy with? Not the best option in my opinion in case of security patch releases etc.
3. Any other options I would leverage to have my apps safe from such issues?

Here's the commit I am referring to:

https://github.com/abiosoft/caddy-docker/commit/be00e81ea112799ee654243fb6fb3e02307cf898#diff-04c6e90faac2675aa89e2176d2eec7d8R110

**Comment by abiosoft** [comment]
Sorry about that.

1. I will try to work on an email subscription to notify users ahead of any breaking change like this.
2. I'd recommend not using using `:latest` and use something like `:0.9.3`. No breaking change is going to happen anytime soon. This was a reversal of the only breaking change ever made; in 0.9.1 that lead to volume permission issues. 
3. Even though I am sure of no breaking change on the way, I will still advise to stick to `:0.9.3` and update when new releases are out. Or you can create an image that builds on`:latest` and override the things you want.

If you wouldn't mind, I'd like to know what change broke your server. 

Sorry, and thanks.

**Comment by pavlo** [comment]
Hey! Thanks for your reply, yeah, I decided to stick to `:0.9.3` so it should be safe. As to what change broke it - here's it:

Suppose I had this in my `docker-compose` before 0.9.3 came out. Note the second volume declaration that connects a host directory to `/home/caddy/.caddy` in the image. 

```
proxy:
    image: abiosoft/caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/Caddyfile
      - $HOME/.caddy:/home/caddy/.caddy
    depends_on:
      - app
```

Then I ran it (well, we do continuos delivery so we run it a couple of times a day), Caddy obtains SSL certs and stuff from LetsEncrypt and stores it all `/home/caddy/.caddy` in container which is ` $HOME/.caddy` on host. All works just fine up to this moment.

Then `:0.9.3` Caddy image comes out and it is configured to read/cache SSL stuff `/root/.caddy` folder in container. However when I launch my app with the above config it keeps mounting SSL stuff to `/home/caddy/.caddy` which is not used by Caddy in `0.9.3` anymore. 

I re-deployed a couple of times trying to debug the issue (at first I thought it is one of our changes caused it of course) and this eventually led to Let'sEncrypt quota exceeding:

`Error 429 - urn:acme:error:rateLimited - Error creating new cert :: Too many certificates already issued for exact set of domains...`

Hope it describes the issue well. Please let me know if you want me to provide any more details!

**Comment by abiosoft** [comment]
It is the change that led to it because it changed where caddy stores certs. So, the certs weren't persisted anymore and every new container generates new one.

Use `$HOME/.caddy:/root/.caddy` instead and it should work. Provided the certs are still in `$HOME/.caddy`.

Sorry about that.

**Comment by abiosoft** [comment]
You can check https://github.com/abiosoft/caddy-docker#saving-certificates for some tips.

**Comment by pavlo** [comment]
Oh great, thanks! I am going to leverage something like to be safe next time:

> -e "CADDYPATH=/etc/caddycerts"
> -v $HOME/.caddy:/etc/caddycerts

Thank you!
