### ISSUE TITLE
independent caddy-docker versioning

### ISSUE THREAD

**Issue by cgag** [abiosoft/caddy-docker#31]
It would be great if this container was tagged in a way that updates to this repo didn't mutate tags on dockerhub.  We've been using the 0.9.1 tags of this repo for a while, and recently ran into a problem where one of our containers failed to restart.  

It turned out the 0.9.1 tag was mutated when you switched from running as `root` to running as `caddy`, and the restart caused the latest version to be pulled, which was incompatible with our setup.

**Comment by abiosoft** [comment]
Hi, this was a big blunder from me and it is not gonna happen again. Even the breaking change has been reversed as many users had volume permission issues.

You can use `0.9.3` now and tags are henceforth immutable.

Really sorry about that.

**Comment by abiosoft** [comment]
You can check https://github.com/abiosoft/caddy-docker#saving-certificates for some tips.
