### ISSUE TITLE
Debug logging for web server

### ISSUE THREAD

**Issue by pdemro** [abiosoft/caddy-docker#33]
Greetings! 

I understand Caddy has some debug logging capability using the -log flag on the Caddy binary.  Is there a way to output this to a file using the abiosoft/caddy container image?  

The hope is that this debug spam will help me detect when I've made an error in my Caddyfile, or if Caddy is having problems negotiating a certificate on a new domain for some reason.

Thank you in advance!  And thank you for maintaining the image!

Regards,

Phil

**Comment by abiosoft** [comment]
Done
