### ISSUE TITLE
PHP extensions

### ISSUE THREAD

**Issue by DenBeke** [abiosoft/caddy-docker#35]
The only way to add more PHP extensions is forking the Dockerfile and hardcoding them?

**Comment by abiosoft** [comment]
For now, yes.

Do you know of an easy way to install all extensions ?

**Comment by DenBeke** [comment]
I'm afraid I don't know :/

**Comment by ideaman924** [comment]
Some of the essential PHP extensions needed by WordPress + Jetpack has already been merged in. Hopefully we can keep doing this until we have all essentials. Basically see what program screams for what dependency.

**Comment by mestaritonttu** [comment]
Did you test running docker-php-ext-install inside the container?
https://github.com/docker-library/docs/tree/master/php
"How to install more PHP extensions" in the above.

**Comment by pwFoo** [comment]
I have to build my own php image because some extensions missing.

**Comment by JacobiteDE** [comment]
@pwFoo are essential php extensions missing?

you cloud also build your own image by customizing the build
```
# Dockerfile
FROM abiosoft/caddy:php
RUN apk add --no-cache php7-ftp
```
please consider that the extensions must be available as alpine linux package
https://pkgs.alpinelinux.org/packages

**Comment by abiosoft** [comment]
I'll be closing this. @JacobiteDE's comment https://github.com/abiosoft/caddy-docker/issues/35#issuecomment-505781194 seems to be the best way out.
