### ISSUE TITLE
proxy doesn't resolve domain

### ISSUE THREAD

**Issue by MihaMarkic** [abiosoft/caddy-docker#36]
#Trying to figure out why
`proxy / IP:PORT`
works but
`proxy / domain:PORT`
doesn't (times out or bad gateway)
Any idea what can be a problem? If I /bin/sh into caddy container, I can resolve domain to IP.
Using a shared network that supports IPv6.

**Comment by abiosoft** [comment]
Are you using Docker Compose or Kubernetes ?

**Comment by MihaMarkic** [comment]
@abiosoft  Docker compose

**Comment by abiosoft** [comment]
@MihaMarkic hi, is this issue still valid ?

**Comment by MihaMarkic** [comment]
I think this was an issue when I was using more than one network. Since then I reduced to a single network. I guess it's still an issue, don't really know at this point.

**Comment by abiosoft** [comment]
I'll be closing this until someone else have a similar experience.
