### ISSUE TITLE
Reloading configuration doesn't work

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#4]
I tried to reload the configuration to make iterations faster with:

     docker kill -s HUP caddy

But it didn't appear to work. This is my service file I was using btw: http://s.natalian.org/2016-01-10/caddy.service

**Comment by abiosoft** [comment]
Are you running the PHP variant ?

**Comment by kaihendry** [comment]
Yes, see http://s.natalian.org/2016-01-10/caddy.service, the line `ExecStartPre=-/usr/bin/docker pull abiosoft/caddy:php` sets up your Docker image.

**Comment by abiosoft** [comment]
oh I see. I know the reason.

For the PHP variant, the entrypoint is not caddy. I needed to start php-fpm prior to that. Let me see if there's a workaround.

**Comment by abiosoft** [comment]
Good news :smile: 

I have modified the image to have Caddy as PID 1.
You can pull with `docker pull --no-cache abiosoft/caddy:php`.

Your Caddyfile must now include `startup php-fpm` https://github.com/abiosoft/caddy-docker#note. That is the compromise to get Caddy as PID 1 and I believe that's an easy compromise. :blush:

**Comment by abiosoft** [comment]
Apparently, seems  `--no-cache` only works when building images. :unamused:.

You can forcefully remove the image to get it to pull an updated one afterwards.
```
docker rmi -f abiosoft/caddy:php
```

**Comment by abiosoft** [comment]
On a side note, Caddy graceful restart is not with same pid. So, the container will still exit.

**Comment by kaihendry** [comment]
How do I know I have the latest image? Is it 00e2220d8877 ?

**Comment by abiosoft** [comment]
I see you can always update the image by running `docker pull abiosoft/caddy:php` again.

Yeah, that's the latest.

**Comment by kaihendry** [comment]
Can you please teach me to fish? I.e. how did you know that's the latest image hash?

Would be cool to be able to load up Caddy server and know what image & Caddy version I am running.

**Comment by abiosoft** [comment]
I only did a comparison with mine. I don't know of any other way of checking latest hash other than running `docker pull` and checking the hash.

What can be done is to check the caddy version in the image.
```
docker inspect -f "{{json .Config.Labels }}" abiosoft/caddy:php
```

**Comment by abiosoft** [comment]
@kaihendry You can follow up this thread https://github.com/mholt/caddy/issues/416. It is related.
