### ISSUE TITLE
PHP variant has no session support.

### ISSUE THREAD

**Issue by ckeeney** [abiosoft/caddy-docker#42]
Running this php file:
```php
# index.php
<?php
die(session_start());
```
returns 
```
PHP message: PHP Fatal error:  Uncaught Error: Call to undefined function session_start() in /srv/index.php:3
```

PHP docs indicate that [PHP sessions are enabled by default](http://php.net/manual/en/session.installation.php).  Alpine ships PHP sessions as a separate package, `php7-session`.

I think that package should be added to the `abiosoft/caddy:php` image but if not, we should document how to add it.

It may be a good idea to compare `php7 -i` in `abiosoft/caddy:php` to `php -i` in `php:fpm-alpine` and add a few things that people expect to be there.

I solved this for my case with
```Dockerfile
FROM abiosoft/caddy:php
RUN apk --update add --no-cache \
    php7-session \
    && rm -rf /var/cache/apk/*
```

**Comment by abiosoft** [comment]
Fixed. Kindly pull the image again. 

Thanks.
