### ISSUE TITLE
Feature request: VIRTUAL_HOST

### ISSUE THREAD

**Issue by ekkis** [abiosoft/caddy-docker#47]
if you look at https://github.com/BlackGlory/caddy-proxy you'll see that his package automatically regenerates a Caddyfile every time a new docker container gets fired.  it looks at the environment variable, which contains the name we want the container to answer to, and maps appropriately.

it'd be great if this package could do this.  reason: this package has 500+K pulls whilst BlackGlory's has 385 and gets no support.  I can't make it work (I've already spent too much time trying) but I love the functionality

would it be difficult to do?

**Comment by abiosoft** [comment]
The package you made reference to serves a different purpose to this as it is primarily using caddy as a reverse-proxy.

You are not tied to Caddyfile as you can specify yours by mounting one on `/etc/Caddyfile`. 
And `VIRTUAL_HOST` to me is just an environment variable; which Caddyfile supports.

Feel free to re-open this and clarify to me if you think I got you wrong.
