### ISSUE TITLE
PHP message: PHP Fatal error:  Call to undefined function json_decode()

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#5]
JSON decoding is pretty common. Can you please add php-json to the packages?

**Comment by abiosoft** [comment]
I have added it.

You can give it like 15 mins or if that's too long, monitor the build directly here https://hub.docker.com/r/abiosoft/caddy/builds/.

After that, `docker pull abiosoft/caddy:php` to update the image.

Thanks.
