### ISSUE TITLE
Add support for disabling HTTP2

### ISSUE THREAD

**Issue by mnzt** [abiosoft/caddy-docker#50]
This is required for serving WebSocket secure. See https://caddyserver.com/docs/cli#http2.

**Comment by abiosoft** [comment]
You can override with flags by providing addition flags.
The default flags for the container are `--conf /etc/Caddyfile --log stdout`.
```
docker run -it abiosoft/caddy --log stdout --conf /etc/Caddyfile --http2=false
```
