### ISSUE TITLE
What does "Blocking Command" mean?

### ISSUE THREAD

**Issue by adriel** [abiosoft/caddy-docker#51]
I get this when I start up the caddy:php server, any ideas what is meant by this?
I know it's just an info notice, just curious what (and why) it's blocking.

    2017/03/21 08:27:53 [INFO] Blocking Command:"php-fpm7 "

**Comment by abiosoft** [comment]
That is minor and can be disregarded. [startup](https://caddyserver.com/docs/startup) directive is being used to start php-fpm7.
