### ISSUE TITLE
Security?

### ISSUE THREAD

**Issue by rmoriz** [abiosoft/caddy-docker#52]
Why does caddy run as root, again? Why did you remove the separation with 0.9.3?

https://github.com/abiosoft/caddy-docker/commit/be00e81ea112799ee654243fb6fb3e02307cf898

**Comment by abiosoft** [comment]
Permission issues primarily with mounted volumes.

**Comment by rmoriz** [comment]
You need to sync the group and group ids of both containers. e.g. on debian based boxes `www-data` has a gid of 33, on alpine it's 82 https://git.alpinelinux.org/cgit/aports/tree/main/apache2/apache2.pre-install.

**Comment by abiosoft** [comment]
I definitely prefer it to run without root. But after having to deal with multiple permission issues, I had to revert.

If you have some time on your hands, do you mind raising a PR ?

Thanks.
