### ISSUE TITLE
unable to bind listening socket for address '127.0.0.1:9000': Address in use (98)

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#6]
I want to host several PHP sites in one container since having a container for each of my little sites is a bit overkill.

However if I duplicate `fastcgi / 127.0.0.1:9000 php` it borks with a Address in use error.

Here are my configs: http://s.natalian.org/2016-02-11/bug.tar

Is there a better way to share one PHP FPM?

**Comment by kaihendry** [comment]
Oh, I removed `startup php-fpm` and now it works. Argh. Wish `startup php-fpm` wasn't there to begin with.

**Comment by abiosoft** [comment]
Yeah, put it only in your primary Caddyfile and remove it from the vhost files.

**Comment by kaihendry** [comment]
I tried putting `startup php-fpm` in my primary Caddyfile like so:

```
import  vhosts/*
startup php-fpm
```

But it didn't work.

**Comment by abiosoft** [comment]
Oh hmmm. That's true. 

You have to use it only once.

**Comment by abiosoft** [comment]
You can use this hack till there's a better way out. Declare a useless catch all block.
```
import vhosts/*

:80 {
    internal /
    startup php-fpm
}
```

**Comment by kaihendry** [comment]
Oh, how does the syntax work for :443 as well? Another block?

**Comment by abiosoft** [comment]
:80, :443 {
    internal /
    startup php-fpm
    tls off # so it won't generate useless certs for requests here.
}

**Comment by kaihendry** [comment]
[Didn't work for me.](http://s.natalian.org/2016-02-11/1455175757_1912x1036.png)
```
import  vhosts/*
:80, :443 {
internal /
startup php-fpm
tls off # so it won't generate useless certs for requests here.
}
```

**Comment by abiosoft** [comment]
Hmmm.

Okay. Remove that use startup php-fpm in only of the vhosts.

I'll look for a solution.
