### ISSUE TITLE
always 502 when using proxying in docker

### ISSUE THREAD

**Issue by ZeekoZhu** [abiosoft/caddy-docker#63]
here is my Caddyfile
```
tools.xxxx.com {
	proxy / localhost:5004 {
		transparent
	}
#	log / /home/caddy/logs/tools_access.log
}
```
But when I run caddy on the host directly, everything works well

**Comment by abiosoft** [comment]
what is running on localhost:5004 ?

Are you using Docker Machine or Docker for Mac ?

**Comment by ZeekoZhu** [comment]
I'm using docker on Ubuntu 16.04 kernel 4.4.0

**Comment by abiosoft** [comment]
I am not sure if `localhost` is how you reach the host from a docker container. That is most likely where to problem is. You can try reaching that port from inside the container.

I believe that Caddy has no role to play in this, but rather communication between container and host.

Feel free to reopen if we ascertain it is an issue with Caddy.
