### ISSUE TITLE
Use alpine:latest

### ISSUE THREAD

**Issue by joelchen** [abiosoft/caddy-docker#66]
Would like to use alpine:latest, 3.6 at the time of this writing.

**Comment by abiosoft** [comment]
`:latest` is discouraged as you are not guaranteed to have reproducible builds with it. Hence, the tags.

Any particular reason you want 3.6 ?

**Comment by joelchen** [comment]
@abiosoft I want 3.6 so that I could use the same --spider switch consistent with other alpine 3.6 containers for wget.

**Comment by abiosoft** [comment]
okay. I can only update `:latest` but not any tagged image. e.g. `:0.10.6`.

**Comment by joelchen** [comment]
@abiosoft Alright, thank you.

**Comment by joelchen** [comment]
@abiosoft Has alpine:latest been updated and pushed to Docker Hub?

**Comment by abiosoft** [comment]
I've changed the `:latest` to use 3.6.
