### ISSUE TITLE
Image is not complying with Caddy license

### ISSUE THREAD

**Issue by adisbladis** [abiosoft/caddy-docker#68]
Official binaries of Caddy are now under EULA.
This makes the images distributed on docker hub non-compliant.

https://github.com/mholt/caddy/blob/master/dist/EULA.txt

**Comment by abiosoft** [comment]
Hi,

I am fully aware and I plan to modify the docker images to build from source as soon as time permits me.

Thanks.

**Comment by viroos** [comment]
Is it only about 0.10.9 and 0.10.9-php images or does it affect older builds as well?

**Comment by abiosoft** [comment]
0.10.9 upwards

**Comment by viroos** [comment]
how about just removing 0.10.9 to avoid mistakes?

**Comment by abiosoft** [comment]
Fixed
