### ISSUE TITLE
0.10.9 contains sponsor header

### ISSUE THREAD

**Issue by princemaple** [abiosoft/caddy-docker#69]
Hi @abiosoft 

The latest build (0.10.9, published to docker hub 3hrs before this issue) contains the sponsor header that caddy master has already removed. Could you pull latest caddy and rebuild?

Thanks a lot for quickly setting up the built from source image.

Regards,
Po

**Comment by abiosoft** [comment]
It is preferred to always build from tag releases for stability.
If you are not very specific about some features in 0.10.9, I would suggest staying on 0.10.8 until a new release is tagged.

I might be willing to do a one-off compromise for `:latest` if there is strong need for it.

**Comment by princemaple** [comment]
You are right. Somehow I thought the image was built from HEAD from your local repo, even I read through your Dockerfile. 👍 

I'll leave this open in case others having the same question. Feel free to close if you think it's not necessary.
