### ISSUE TITLE
Question: why not go get?

### ISSUE THREAD

**Issue by princemaple** [abiosoft/caddy-docker#73]
Hi @abiosoft 

this is just a question for you about your latest built-from-source image.
why did you choose to clone the plugin repo (caddy-git in this case) instead of simply `go get` it?

I've played around your dockerfile and got to this version that allows installing plugins, FYI
```Dockerfile
# plugins
ARG plugins="github.com/abiosoft/caddy-git"

RUN echo "package caddyhttp" > /go/src/github.com/mholt/caddy/caddyhttp/plugins.go
RUN for plugin in $(echo $plugins | tr "," " "); do \
      go get $plugin; \
      echo "import _ \"$plugin\"" >> \
        /go/src/github.com/mholt/caddy/caddyhttp/plugins.go; \
    done
```

Thanks a lot for your work!

**Comment by abiosoft** [comment]
This works actually. Though I'd prefer if the users do not need to remember the repo names and plugin names should suffice.

I'd build on this and bring back the plugins build arg again.

**Comment by princemaple** [comment]
I started with this, hoping the same (i.e. just using the names)

```Dockerfile
RUN echo "package caddyhttp" > /go/src/github.com/mholt/caddy/caddyhttp/plugins.go
RUN for plugin in $(echo $plugins | tr "," " "); do \
      repo_name=`echo $plugin | sed -e 's/^\(\w\+\)\/\(\w\+\)\(\/.*\)\?/\1\/\2/g'`; \
      git clone "https://github.com/$repo_name" "/go/src/github.com/$repo_name"; \
      cd "/go/src/github.com/$repo_name"; \
      go get ./...; \
      echo "import _ \"github.com/$plugin\"" >> \
        /go/src/github.com/mholt/caddy/caddyhttp/plugins.go; \
    done
```

```
repo_name=`echo $plugin | sed -e 's/^\(\w\+\)\/\(\w\+\)\(\/.*\)\?/\1\/\2/g'`
```
is because of `https://github.com/hacdias/filemanager/tree/master/caddy/filemanager`

Then I quickly ran into this `https://hub.blitznote.com/src/caddy.upload`.
Then I threw my hands in the air, cursed golang package system, and tried `go get`... :)

**Comment by princemaple** [comment]
https://github.com/mholt/caddy/blob/baf6db5b570e36ea2fee30d50f879255a5895370/caddyhttp/httpserver/plugin.go#L494
https://github.com/mholt/caddy/blob/baf6db5b570e36ea2fee30d50f879255a5895370/caddyhttp/httpserver/plugin.go#L507
https://github.com/mholt/caddy/blob/baf6db5b570e36ea2fee30d50f879255a5895370/caddyhttp/httpserver/plugin.go#L511-L512
*Shrug* don't seem very unify-able.

**Comment by abiosoft** [comment]
Haha, there is a better way out. But I currently have my hands full. I should have something before end of the day.

Thanks for the efforts.

**Comment by princemaple** [comment]
Thank YOU. 👍

**Comment by abiosoft** [comment]
You can now get a custom docker image this way.
```
docker build --build-arg \
    plugins=filemanager,git,realip\
    github.com/abiosoft/caddy-docker.git
```

I added package name fetching to caddyplug, the experimental Caddy plugin management tool. Which made the job easier as you can see here.
https://github.com/abiosoft/caddy-docker/blob/master/Dockerfile#L19-L24
