### ISSUE TITLE
Using -v to replace Caddyfile issues Permission Denied error

### ISSUE THREAD

**Issue by justyntemme** [abiosoft/caddy-docker#74]
~~~~
sudo docker run -p 2015:2015 -p 7002:443 -p 7003:80 -p 7001:7001 -v $(pwd)/Caddyfile:/etc/Caddyfile docker.io/abiosoft/caddy:php
~~~~

Leads to error 
`2017/10/01 17:59:21 loading Caddyfile via flag: open /etc/Caddyfile: permission denied`

**Comment by abiosoft** [comment]
I can not reproduce this. What platform are you trying this on ?

**Comment by justyntemme** [comment]
Fedora 26. I'm thinking SElinux issue. Will test and report back.

**Comment by justyntemme** [comment]
Issue is with docker not with Caddy. Docker does not allow Symlinks to be mounted with -v
