### ISSUE TITLE
Please add http.cache plugin

### ISSUE THREAD

**Issue by waja** [abiosoft/caddy-docker#75]
It would be very great to add the [http.cache](https://caddyserver.com/docs/http.cache) plugin to the image.

**Comment by abiosoft** [comment]
I think it would be better to have a set of useful plugins under a tag. I just haven't figured the best tag name to use. Maybe `abiosoft/caddy:essential`, though I would prefer a shorter word.

**Comment by astraldragon** [comment]
I'm still fairly new to docker, and caddy as well.  I'd like to use the login plugin.  Could it be exposed through an environment variable?

```yaml
environment:
  - CADDY_PLUGINS=http.git,http.login
```

**Comment by OmgImAlexis** [comment]
@astraldragon that'd require caddy to be downloaded at runtime instead of build time.

**Comment by ryancurrah** [comment]
i would like the datadog plugin, im wondering if two containers might be a good idea, one minimal and one with all the plugins installed?

**Comment by abiosoft** [comment]
I think I'll be going for `lite` and `all`.

**Comment by ryancurrah** [comment]
@abiosoft do you want some help?

**Comment by abiosoft** [comment]
No one turns down help 😉 
> @abiosoft do you want some help?

**Comment by ryancurrah** [comment]
How can I help? Want me to try creating a `all` image and create a PR?

**Comment by tehniemer** [comment]
Semi off topic, but seemed a better place to ask then start a new "issue"

I need the http.reauth plugin and PHP and I'm not totally sure how to build that. I'm pretty new to docker and very new to Caddy.

```
$ docker build -d \
    -e "CADDYPATH=/etc/caddycerts" \
    -v $HOME/.caddy:/etc/caddycerts \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    plugins=git,reauth \
    github.com/abiosoft/caddy-docker.git
```

Something like that? Not sure where PHP would come into play.

**Comment by abiosoft** [comment]
That will require two steps except you're using docker-compose.

Firstly, build the image.
```
docker build -t caddyphp -e plugins=git,reauth github.com/abiosoft/caddy-docker.git#:php
```
Then run it
```
docker run -d \
    -e "CADDYPATH=/etc/caddycerts" \
    -v $HOME/.caddy:/etc/caddycerts \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    caddyphp
```

**Comment by abiosoft** [comment]
By the way, the only reason I haven't gone ahead is deciding which plugins should be the defaults. 
Also, `all` is also not possible at the moment because grpc plugin is not building.

**Comment by tehniemer** [comment]
Thanks, I've never built a image before, clearly ;)

**Comment by tehniemer** [comment]
Ran into an issue building the image. I get an error ```unknown shorthand flag: 'e' in -e``` I tried replacing ```-e``` with ```--build-arg``` and got the error ```unable to prepare context: unable to find 'git': exec: "git": executable file not found in $PATH```

**Comment by abiosoft** [comment]
Yeah, it was meant to be `--build-arg` for building. I've corrected the post. You got that error because you need to have git installed on your server.

**Comment by tehniemer** [comment]
Awesome, thanks again. I installed git and it worked as expected.

**Comment by amasover** [comment]
I did a

```
docker build \
--build-arg plugins=git,jwt,login \
github.com/abiosoft/caddy-docker.git -t amasover/caddy
```

And then a

```
docker run -d \
    -e "CADDYPATH=/etc/caddycerts" \
    -v $HOME/.caddy:/etc/caddycerts \
    -v $(pwd)/Caddyfile:/etc/Caddyfile \
    amasover/caddy
```

I want to set up the login plugin with Google OAuth, so I have this in my Caddyfile:

```
login {
    google client_id=theclientid,client_secret=thesecret
}
```

When I start Caddy, I get `Error during parsing: Unknown directive 'google'`. I get the same if I try to use any other directives that should be defined by the login plugin. Does your `caddyplug` tool update the Caddy directives?

**Comment by abiosoft** [comment]
@amasover kindly open another issue.

**Comment by amasover** [comment]
@abiosoft 

I think I found my problem. I should have had:

```
www.domain.com {
    login {
        google client_id=theclientid,client_secret=thesecret
    }
}
```

It looks like your script installed the directives correctly; I was just using them incorrectly.

**Comment by abiosoft** [comment]
This plugin will be included starting from the next version of Caddy.
