### ISSUE TITLE
browse times not in local time

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#8]
Noticed the times of my uploaded files were wrong. Is there some sort of ENV variable for setting for example `Asia/Singapore`?

**Comment by abiosoft** [comment]
That's tricky. 

If its just for php, your best bet is to have `ini_set('date.timezone', 'Asia/Singapore')` in your php source. But if it is os level, you may need to extend this image and do this http://wiki.alpinelinux.org/wiki/Setting_the_timezone.

**Comment by abiosoft** [comment]
Due to inactivity, I'll be closing this. 

I'd still like to know how you fixed this. Thanks.
