### ISSUE TITLE
Missing dependencies for googlecloud plugin

### ISSUE THREAD

**Issue by brianmhunt** [abiosoft/caddy-docker#85]
To have plugin `googlecloud` the image needs:

```Dockerfile
RUN apk add --no-cache gcc musl-dev
ARG plugins="googlecloud"
```

Then in the "Final" stage

```Dockerfile
RUN apk add --no-cache ca-certificates
```

Otherwise the image compilation fails or Caddy errors with "Unsupported DNS provider"

**Comment by abiosoft** [comment]
This is probably new, I have had success with the plugin before. 

Thanks for spotting this.

**Comment by brianmhunt** [comment]
Thanks for the quick acknowledgment.

Note, my original comment was incorrect; `ca-certificates` has to be added in the "Final" stage, not the builder stage.

**Comment by abiosoft** [comment]
`openssh-client` requires `ca-certificates`, so it is always installed.

**Comment by abiosoft** [comment]
Okay, fixed now. Sorry this came a bit late, didn't have much time on my hands.
