### ISSUE TITLE
upload_max_filesize

### ISSUE THREAD

**Issue by kaihendry** [abiosoft/caddy-docker#9]
Default php.ini is `upload_max_filesize = 2M` which is a bit on the small size. Be good to nice way to override this (without mapping php.ini out) or just have better defaults like at least 10MB. Cheers!

**Comment by abiosoft** [comment]
As a fallback option, you can always use `ini_set` in your php code to override any php.ini settings.

That being said, I will look at the possible options of allowing users to modify php.ini values. Suggestions are welcome.

Thanks.

**Comment by andrewbanchich** [comment]
@kaihendry You can the following to a `docker-compose.yml` file for the image you're using if you us `docker-compose`:

`volumes:`
`    - "./php.ini:/usr/local/etc/php/php.ini"`

Then just create a `php.ini` file in the same directory with `upload_max_filesize = 2M` inside it and run `docker-compose up -d`.

This will bind the local `php.ini` file to the file in the docker container so you can easily adjust the upload filesize limit.

**Comment by abiosoft** [comment]
Thanks for your suggestion @andrewbanchich 

@kaihendry Sorry I haven't been able to help you look at this properly.

A quick execution of `php --ini` in the container gives
```
/srv # php --ini
Configuration File (php.ini) Path: /etc/php5
Loaded Configuration File:         /etc/php5/php.ini
Scan for additional .ini files in: /etc/php5/conf.d
Additional .ini files parsed:      /etc/php5/conf.d/curl.ini,
/etc/php5/conf.d/gd.ini,
/etc/php5/conf.d/iconv.ini,
/etc/php5/conf.d/json.ini,
/etc/php5/conf.d/mysql.ini,
/etc/php5/conf.d/mysqli.ini,
/etc/php5/conf.d/openssl.ini,
/etc/php5/conf.d/pgsql.ini,
/etc/php5/conf.d/phar.ini,
/etc/php5/conf.d/sqlite3.ini,
/etc/php5/conf.d/zip.ini
```

That means you can add an additional ini file in `/etc/php5/conf.d/` and it will be loaded.
You can create a custom ini file with `upload_max_filesize = 2M` as contents and add it to that path in your container. 

Example
```
docker run -v /path/to/custom.ini:/etc/php5/conf.d/custom.ini abiosoft/caddy:php
```

Feel free to reopen if that does not work.
