### ISSUE TITLE
Support net plugin (and maybe others)

### ISSUE THREAD

**Issue by frozenice** [abiosoft/caddy-docker#90]
First off , let me say how fantastic your work is! Now, I was trying to build an image with the [net](https://caddyserver.com/docs/net) plugin (`plugins=net` via build-args). This failed, because it didn't find the plugin.
A quick peek into builder and caddyplug suggests to me, that it only searches the official Caddy repo for plugins. Maybe this could be extended to allow custom plugin locations (e.g. `packages=github.com/pieterlouw/caddy-net/caddynet`)?
I'm no golang-er, so sadly won't be able to contribute a PR. In the meantime, I compiled Caddy myself with the net plugin (easy enough via go container).

**Comment by abiosoft** [comment]
The are only two server type plugins, net and dns. Since they are just two, I can hardcode it for now. If they happen to grow in number, we can look for a better way to fetch them.

I am still looking for a better way to fetch plugin info, especially the stable versions. Right now the plugins are built off master branch.

**Comment by abiosoft** [comment]
It is supported now.

**Comment by frozenice** [comment]
Thanks!

> The are only two server type plugins

True, hardcoding works for those. But the issue that the code for plugins could live outside of the main repo still exists. I haven't looked around if there any besides `net` though... just a thought (and what I meant with "and maybe others").
Maybe that would also make it easier for some caddy plugin authors to test their plugin (the easy creation of a docker image, that is) - but maybe the manual way is quick enough, too (I have no experience with writing caddy plugins).

> Right now the plugins are built off master branch.

From what I read (again, I'm no golang-er), stuff that is built with `go get` etc. is always pulled from master (`get` doesn't even support branches and / or tags, I think) and the official philosophy is something like "master is always stable / buildable". But I don't know if every go project is structured that way.
My intuition also says you should be able to pin versions, but maybe it's not such a big problem.
