### ISSUE TITLE
Can't start container tag 0.10.12

### ISSUE THREAD

**Issue by pascalandy** [abiosoft/caddy-docker#99]
Can't start the image.

Stuck into:

```
overall progress: 0 out of 1 tasks
1/1: starting  [============================================>      ]
```

## error message 

using `docker service logs --name`

```
invalid boolean value "$ACME_AGREE" for -agree: strconv.ParseBool: parsing "$ACME_AGREE": invalid syntax
```

Also here: https://github.com/abiosoft/caddy-docker/blob/24eb76481d9ed3eaafda1d769749ce50b89ddec8/Doc

There should be spaces:
```
CMD [ "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=$ACME_AGREE" ]
```

I built the image using the space but I have the space issue.

**Comment by abiosoft** [comment]
I can't seem to reproduce this. What command did you use to start your container ? 
Also, the source link shared above is broken.

**Comment by pascalandy** [comment]
Wow, you're fast. I was about to close the issue.

It's my bad, I only updated the Dockerfile (was running 0.10.10). I realized there is other deps outside the Dockerfile. All running smoothly now!

**Comment by pascalandy** [comment]
But the spaces should be fixed.

```
CMD [ "--conf", "/etc/Caddyfile", "--log", "stdout", "--agree=$ACME_AGREE" ]
```
